name: Deploy to S3

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GITHUB_TOKEN }}
          aws-secret-access-key: ${{ secrets.GITHUB_TOKEN }}
          aws-region: us-east-1 # Replace with your AWS region

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://dlg-portfolio --delete --acl public-read # Replace with your bucket name
