

name: Deploy to S3

on:
  push:
    branches:
      - main  # Or your default branch

permissions:
  id-token: write
  contents: write


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ACTIONS }}
          aws-region: us-east-1
          audience: sts.amazonaws.com # Replace with your AWS region

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://dlg-portfolio --delete --acl public-read # Replace with your bucket name
